# Generated by Django 4.1.5 on 2023-03-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, verbose_name='Телефон'),
        ),
    ]
