# Generated by Django 4.1.5 on 2023-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_readers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='phone',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Телефон'),
        ),
    ]
