# Generated by Django 4.1.5 on 2023-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='phone_number',
            field=models.BigIntegerField(verbose_name='Телефон'),
        ),
    ]
