# Generated by Django 4.1.5 on 2023-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_readers_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='active_books',
            field=models.ManyToManyField(blank=True, null=True, to='service.book', verbose_name='Активные книги'),
        ),
    ]
