# Generated by Django 4.1.5 on 2023-03-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_readers_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readers',
            name='phone_number',
            field=models.PositiveBigIntegerField(verbose_name='Телефон'),
        ),
    ]
